---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - persistent_volume.yaml
  - persistent_volume_claim.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
