---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
